package com.restaurant.repository;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import com.restaurant.config.ConnectionFactory;
import com.restaurant.dto.EmployeeDTO;
import com.restaurant.model.Employee;
import com.restaurant.model.User;
import com.restaurant.model.enums.AccessProfile;

public class EmployeeRepository {
    
    public Employee save(EmployeeDTO dto) {
        String sql = "INSERT INTO employees (name, surname, cpf, role, has_access, user_id) VALUES (?, ?, ?, ?, ?, ?)";

        try (Connection conn = ConnectionFactory.getConnection();
            PreparedStatement stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            stmt.setString(1, dto.name());
            stmt.setString(2, dto.surname());
            stmt.setString(3, dto.cpf());
            stmt.setString(4, dto.role());
            stmt.setBoolean(5, dto.hasAccess());

            if (dto.user() != null) {
                stmt.setLong(6, dto.user().getId());
            } else {
                stmt.setNull(6, Types.BIGINT);
            }

            stmt.executeUpdate();

            try (ResultSet rs = stmt.getGeneratedKeys()) {
                if(rs.next()) {
                    return new Employee(
                        rs.getLong(1),
                        dto.name(),
                        dto.surname(),
                        dto.cpf(),
                        dto.role(),
                        dto.hasAccess(),
                        dto.user()
                    );
                } else {
                    throw new SQLException("Could not get ID generated by DB");
                }
            }

        } catch (SQLException e) {
            throw new RuntimeException("Could not add employee to DB");
        }
    }


    public List<Employee> searchAll() {
        String sql = "SELECT e.id AS employee_id, e.name, e.surname, e.cpf, e.role, e.has_access, " +
                     "u.id AS user_id, u.login, u.password, u.access_profile FROM employees e " +
                     "LEFT JOIN users u ON e.user_id = u.id"; 
        
        try (Connection conn = ConnectionFactory.getConnection();
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery()) {

            List<Employee> employees = new ArrayList<>();
            while(rs.next()) {
                Employee someEmployee = mapResultSetToEmployee(rs);
                employees.add(someEmployee);
            }
            return employees;

        } catch (SQLException e) {
            throw new RuntimeException("Could not retrieve all employees from DB");
        }
    }


    public Optional<Employee> searchById(Long id) {
        String sql = "SELECT e.id AS employee_id, e.name, e.surname, e.cpf, e.role, e.has_access, " +
                     "u.id AS user_id, u.login, u.password, u.access_profile FROM employees e " +
                     "LEFT JOIN users u ON e.user_id = u.id WHERE e.id = ?"; 

        try (Connection conn = ConnectionFactory.getConnection();
            PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setLong(1, id);
            try (ResultSet rs = stmt.executeQuery()) {
                if(rs.next()) {
                    return Optional.of(mapResultSetToEmployee(rs));
                }
            }

        } catch (SQLException e) {
            throw new RuntimeException("Could not retrieve employee from DB by ID");
        }
        return Optional.empty();
    }


    public Optional<Employee> searchByCpf(String cpf) {
        String sql = "SELECT e.id AS employee_id, e.name, e.surname, e.cpf, e.role, e.has_access, " +
                     "u.id AS user_id, u.login, u.password, u.access_profile FROM employees e " +
                     "LEFT JOIN users u ON e.user_id = u.id WHERE e.cpf = ?"; 
        
        try (Connection conn = ConnectionFactory.getConnection();
            PreparedStatement stmt = conn.prepareStatement(sql)) {
            
            stmt.setString(1, cpf);
            try (ResultSet rs = stmt.executeQuery()) {
                if(rs.next()) {
                    return Optional.of(mapResultSetToEmployee(rs));
                }
            }

        } catch (SQLException e) {
            throw new RuntimeException("Could not retrieve employee from DB by CPF");
        }
        return Optional.empty();
    }


    public Employee update(EmployeeDTO dto) {
        String sql = "UPDATE employees SET name = ?, surname = ?, cpf = ?, role = ?, has_access = ?, user_id = ? WHERE id = ?";

        try (Connection conn = ConnectionFactory.getConnection();
            PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setString(1, dto.name());
            stmt.setString(2, dto.surname());
            stmt.setString(3, dto.cpf());
            stmt.setString(4, dto.role());
            stmt.setBoolean(5, dto.hasAccess());

            if (dto.user() != null) {
                stmt.setLong(6, dto.user().getId());
            } else {
                stmt.setNull(6, Types.BIGINT);
            }

            stmt.setLong(7, dto.id());

            stmt.executeUpdate();

            return searchById(dto.id())
                .orElseThrow(() -> new SQLException("Could not retrieve updated employee data"));

        } catch (SQLException e) {
            throw new RuntimeException("Could not update employee in DB");
        }
    }


    public void delete(Long id) {
        String sql = "DELETE FROM employees WHERE id = ?";

        try(Connection conn = ConnectionFactory.getConnection();
            PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setLong(1, id);
            stmt.executeUpdate();

        } catch (SQLException e) {
            throw new RuntimeException("Could not delete employee from DB");
        }
    }


    
    private Employee mapResultSetToEmployee(ResultSet rs) throws SQLException {

        User user;
        rs.getLong("user_id");

        if (!rs.wasNull()) {
            user = new User(
                rs.getLong("user_id"),
                rs.getString("login"),
                rs.getString("password"),
                AccessProfile.valueOf(rs.getString("access_profile"))
            );
        } else {
            user = null;
        }

        return new Employee(
            rs.getLong("employee_id"),
            rs.getString("name"),
            rs.getString("surname"),
            rs.getString("cpf"),
            rs.getString("role"),
            rs.getBoolean("has_access"),
            user
        );
    }
}
