package com.restaurant.repository;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import com.restaurant.config.ConnectionFactory;
import com.restaurant.dto.EmployeeDTO;
import com.restaurant.model.Employee;
import com.restaurant.model.User;
import com.restaurant.model.enums.AccessProfile;
import com.restaurant.model.enums.Role;

public class EmployeeRepository {
    
    public Employee save(EmployeeDTO employeeDTO) {
        String sql = "INSERT INTO employees (cpf, name, surname, role, user_id) VALUES (?, ?, ?, ?, ?)";

        try (Connection conn = ConnectionFactory.getConnection();
            PreparedStatement stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            stmt.setString(1, employeeDTO.name());
            stmt.setString(2, employeeDTO.surname());
            stmt.setString(3, employeeDTO.cpf());
            stmt.setString(4, employeeDTO.role().name());

            if (employeeDTO.user() != null) {
                stmt.setLong(5, employeeDTO.user().getId());
            } else {
                stmt.setNull(5, Types.BIGINT);
            }

            stmt.executeUpdate();

            try (ResultSet rs = stmt.getGeneratedKeys()) {
                if(rs.next()) {
                    return new Employee(
                        rs.getLong(1),
                        employeeDTO.name(),
                        employeeDTO.surname(),
                        employeeDTO.cpf(),
                        employeeDTO.role(),
                        employeeDTO.user()
                    );
                } else {
                    throw new SQLException("Could not get ID generated by DB");
                }
            }

        } catch (SQLException e) {
            throw new RuntimeException("Could not add employee to DB");
        }
    }


    public List<Employee> searchAll() {
        String sql = "SELECT e.id AS employee_id, e.cpf, e.name, e.surname, e.role, " +
                     "u.id AS user_id, u.login, u.password, u.access_profile FROM employees e " +
                     "LEFT JOIN users u ON e.user_id = u.id"; 

        try (Connection conn = ConnectionFactory.getConnection();
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery()) {

            List<Employee> employees = new ArrayList<>();
            while(rs.next()) {
                Employee someEmployee = mapResultSetToEmployee(rs);
                employees.add(someEmployee);
            }
            return employees;

        } catch (SQLException e) {
            throw new RuntimeException("Could not retrieve all employees from DB");
        }
    }


    public Optional<Employee> searchById(Long id) {
        String sql = "SELECT e.id AS employee_id, e.cpf, e.name, e.surname, e.role, " +
                     "u.id AS user_id, u.login, u.password, u.access_profile FROM employees e " +
                     "LEFT JOIN users u ON e.user_id = u.id WHERE e.id = ?"; 

        try (Connection conn = ConnectionFactory.getConnection();
            PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setLong(1, id);
            try(ResultSet rs = stmt.executeQuery()) {
                if(rs.next()) {
                    return Optional.of(mapResultSetToEmployee(rs));
                }
            }

        } catch (SQLException e) {
            throw new RuntimeException("Could not retrieve employee from DB");
        }
        return Optional.empty();
    }


    public void update(EmployeeDTO employeeDTO) {
        String sql = "UPDATE employees SET cpf = ?, name = ?, surname = ?, role = ?, user_id = ? WHERE id = ?";

        Optional<Employee> currentEmployee = searchById(employeeDTO.id());

        if (currentEmployee.isPresent()){

            try (Connection conn = ConnectionFactory.getConnection();
                PreparedStatement stmt = conn.prepareStatement(sql)) {

                stmt.setString(1, employeeDTO.name());
                stmt.setString(2, employeeDTO.surname());
                stmt.setString(3, employeeDTO.cpf());
                stmt.setString(4, employeeDTO.role().name());
                stmt.setLong(5, employeeDTO.user().getId());
                stmt.setLong(6, employeeDTO.id());

                stmt.executeUpdate();

            } catch (SQLException e) {
                throw new RuntimeException("Could not update employee in DB");
            }
        }
    
    }


    public void delete(Long id) {
        String sql = "DELETE FROM employees WHERE id = ?";

        try(Connection conn = ConnectionFactory.getConnection();
            PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setLong(1, id);
            stmt.executeUpdate();

        } catch (SQLException e) {
            throw new RuntimeException("Could not delete employee from DB");
        }
    }


    private Employee mapResultSetToEmployee(ResultSet rs) throws SQLException {

        User user;
        rs.getLong("user_id");

        if (!rs.wasNull()) {
            user = new User(
                rs.getLong("user_id"),
                rs.getString("login"),
                rs.getString("password"),
                AccessProfile.valueOf(rs.getString("access_profile"))
            );
        } else {
            user = null;
        }

        return new Employee(
            rs.getLong("employee_id"),
            rs.getString("name"),
            rs.getString("surname"),
            rs.getString("cpf"),
            Role.valueOf(rs.getString("role")),
            user
        );
    }
}
