package com.restaurant.repository;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import com.restaurant.config.ConnectionFactory;
import com.restaurant.dto.OrderDTO;
import com.restaurant.model.Ingredient;
import com.restaurant.model.Order;
import com.restaurant.model.enums.CommChannel;
import com.restaurant.model.enums.MeasurementUnit;
import com.restaurant.model.enums.OrderStatus;

public class OrderRepository {
    
    public Order save(OrderDTO dto) {
        String sql = "INSERT INTO orders (amount, date, status, contact, contact_channel, ingredient_id) VALUES (?, ?, ?, ?, ?, ?)";
    
        try(Connection conn = ConnectionFactory.getConnection();
            PreparedStatement stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            
            stmt.setDouble(1, dto.amount());
            stmt.setObject(2, LocalDate.now());
            stmt.setString(3, dto.status().name());
            stmt.setString(4, dto.contact());
            stmt.setString(5, dto.contactChannel().name());
            stmt.setLong(6, dto.ingredient().getId());

            stmt.executeUpdate();

            try(ResultSet rs = stmt.getGeneratedKeys()) {
                if(rs.next()) {
                    Long generatedId = rs.getLong(1);
                    return searchById(generatedId)
                        .orElseThrow(() -> new SQLException("Could not retrieve saved order data"));
                } else {
                    throw new SQLException("Could not get ID generated by DB");
                }
            }
                
        } catch (SQLException e) {
            throw new RuntimeException("Could not add order to DB");
        }

    }


    public List<Order> searchAll() {
        String sql = "SELECT o.id AS order_id, o.amount, o.date, o.status, o.contact, o.contact_channel, " + 
                     "i.id AS ingredient_id, i.name, i.measurement_unit, i.current_amount, i.minimum_stock FROM orders o " +
                     "LEFT JOIN ingredients i ON o.ingredient_id = i.id";

        try(Connection conn = ConnectionFactory.getConnection();
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery()) {

            List<Order> orders = new ArrayList<>();
            while(rs.next()) {
                Order someOrder = mapResultSetToOrder(rs);
                orders.add(someOrder);
            }
            return orders;

        } catch (SQLException e) {
            throw new RuntimeException("Could not retrieve all orders from DB");
        }
    }


    public Optional<Order> searchById(Long id) {
        String sql = "SELECT o.id AS order_id, o.amount, o.date, o.status, o.contact, o.contact_channel, " + 
                     "i.id AS ingredient_id, i.name, i.measurement_unit, i.current_amount, i.minimum_stock FROM orders o " +
                     "LEFT JOIN ingredients i ON o.ingredient_id = i.id WHERE o.id = ?";

        try(Connection conn = ConnectionFactory.getConnection();
            PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setLong(1, id);
            try(ResultSet rs = stmt.executeQuery()) {
                if(rs.next()) {
                    return Optional.of(mapResultSetToOrder(rs));
                }
            }

        } catch (SQLException e) {
            throw new RuntimeException("Could not retrieve order from DB by ID");
        }
        return Optional.empty();
    }


    public Order update(OrderDTO dto) {
        String sql = "UPDATE orders SET amount = ?, date = ?, status = ?, contact = ?, contact_channel = ?, ingredient_id = ? WHERE id = ?";

        try(Connection conn = ConnectionFactory.getConnection();
            PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setDouble(1, dto.amount());
            stmt.setObject(2, dto.date());
            stmt.setString(3, dto.status().name());
            stmt.setString(4, dto.contact());
            stmt.setString(5, dto.contactChannel().name());
            stmt.setLong(6, dto.ingredient().getId());
            stmt.setLong(7, dto.id());

            stmt.executeUpdate();

            return searchById(dto.id())
                .orElseThrow(() -> new SQLException("Could not retrieve updated order data"));

        } catch (SQLException e) {
            throw new RuntimeException("Could not update order in DB");
        }
    }


    public void delete(Long id) {
        String sql = "DELETE FROM orders WHERE id = ?";

        try(Connection conn = ConnectionFactory.getConnection();
            PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setLong(1, id);
            stmt.executeUpdate();

        } catch (SQLException e) {
            throw new RuntimeException("Could not delete order from DB");
        }
    }



    private Order mapResultSetToOrder(ResultSet rs) throws SQLException {

        Ingredient ingredient;
        rs.getLong("ingredient_id");

        if(!rs.wasNull()) {
            ingredient = new Ingredient(
                rs.getLong("ingredient_id"),
                rs.getString("name"),
                MeasurementUnit.valueOf(rs.getString("measurement_unit")),
                rs.getDouble("current_amount"),
                rs.getDouble("minimum_stock")
            );
        } else {
            ingredient = null;
        }

        return new Order(
            rs.getLong("order_id"),
            ingredient,
            rs.getDouble("amount"),
            (LocalDate) rs.getObject("date"),
            OrderStatus.valueOf(rs.getString("status")),
            rs.getString("contact"),
            CommChannel.valueOf(rs.getString("contact_channel"))
        );
    }

}
