/*
 * This source file was generated by the Gradle 'init' task
 */
package com.restaurant;

import static io.javalin.apibuilder.ApiBuilder.delete;
import static io.javalin.apibuilder.ApiBuilder.get;
import static io.javalin.apibuilder.ApiBuilder.path;
import static io.javalin.apibuilder.ApiBuilder.post;

import com.restaurant.config.DatabaseInitializer;
import com.restaurant.controller.EmployeeController;
import com.restaurant.controller.IngredientController;
import com.restaurant.controller.OrderController;
import com.restaurant.controller.UserController;

import io.javalin.Javalin;

public class App {
    public static void main(String[] args) {
        
        DatabaseInitializer.initializeDatabase();

        final IngredientController ingredientController = new IngredientController();
        final OrderController orderController = new OrderController();
        final UserController userController = new UserController();
        final EmployeeController employeeController = new EmployeeController();

        Javalin app = Javalin.create(config -> {

            // Registra Jackson com JavaTimeModule para suportar tipos Java 8 Date/Time (como LocalDate)
            config.jsonMapper(new io.javalin.json.JavalinJackson().updateMapper(mapper -> {
                mapper.registerModule(new com.fasterxml.jackson.datatype.jsr310.JavaTimeModule());
                mapper.disable(com.fasterxml.jackson.databind.SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
            }));

            config.bundledPlugins.enableCors(cors -> {
                cors.addRule(it -> {
                    it.anyHost();
                });
            });

            config.routes.apiBuilder(() -> {

                // Ingredientes
                path("api/ingredients", () -> {
                    get(ingredientController::list);
                    post(ingredientController::register);
                });
                path("api/ingredients/{id}", () -> {
                    get(ingredientController::getById);
                    post(ingredientController::update);
                    delete(ingredientController::delete);
                });


                // Usuarios
                path("api/users", () -> {
                    get(userController::list);
                    post(userController::register);
                });
                path("api/users/{id}", () -> {
                    get(userController::getById);
                    post(userController::update);
                    delete(userController::delete);
                });


                // Funcionarios
                path("api/employees", () -> {
                    get(employeeController::list);
                    post(employeeController::register);
                });
                path("api/employees/{id}", () -> {
                    get(employeeController::getById);
                    post(employeeController::update);
                    delete(employeeController::delete);
                });


                // Pedidos
                path("/api/orders", () -> {
                    get(orderController::list);
                    post(orderController::register);
                });
                path("/api/orders/{id}", () -> {
                    get(orderController::getById);
                    post(orderController::update);
                    delete(orderController::delete);
                });
                
            });
        });

        int port = Integer.parseInt(System.getenv().getOrDefault("PORT", "8080"));
        app.start(port);
        System.out.println("Servidor rodando na porta " + port + "...");
    }
}
